package com.example.subbu.CRUD_App.service.impl;

import com.example.subbu.CRUD_App.dto.StarshipRequestDTO;
import com.example.subbu.CRUD_App.dto.StarshipResponseDTO;
import com.example.subbu.CRUD_App.exception.BadRequestException;
import com.example.subbu.CRUD_App.exception.ResourceNotFoundException;
import com.example.subbu.CRUD_App.model.Starship;
import com.example.subbu.CRUD_App.repository.StarshipRepository;
import com.example.subbu.CRUD_App.service.StarshipService;
import com.example.subbu.CRUD_App.util.StarshipGenerator;
import com.example.subbu.CRUD_App.util.StarshipMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import java.util.Optional;

@Slf4j
@Service
@RequiredArgsConstructor
public class StarshipServiceImpl implements StarshipService {

    private final StarshipRepository starshipRepository;

    @Override
    public StarshipResponseDTO createStarship(StarshipRequestDTO requestDTO) {
        log.info("Entering createStarship() - Generating everything automatically.");
        
        // 1. Generate full Random Starship with tied-together logically matching names
        Starship autoGeneratedStarship = StarshipGenerator.generateRandomStarship();

        // 2. Generate a Unique Registry Number
        String generatedRegistry;
        boolean exists;
        do {
            generatedRegistry = StarshipGenerator.generateRegistryNumber(autoGeneratedStarship.getFaction());
            exists = starshipRepository.findByRegistryNumber(generatedRegistry).isPresent();
        } while (exists);
        
        autoGeneratedStarship.setRegistryNumber(generatedRegistry);
        
        log.info("Auto-generated unique registry number: {}", generatedRegistry);
        log.info("Faction detected: {} | Assigned Name: {} | Home Port: {}", 
                 autoGeneratedStarship.getFaction(), autoGeneratedStarship.getName(), autoGeneratedStarship.getHomePort());

        log.info("Saving auto-generated starship to the database...");
        Starship savedStarship = starshipRepository.save(autoGeneratedStarship);
        log.info("Starship successfully created with ID: {} and Registry: {}", savedStarship.getId(), generatedRegistry);
        
        return StarshipMapper.toDTO(savedStarship);
    }

    @Override
    public StarshipResponseDTO getStarshipById(String id) {
        log.info("Entering getStarshipById() for ID: {}", id);
        Starship starship = starshipRepository.findById(id)
                .orElseThrow(() -> {
                    log.error("Starship not found with ID: {}", id);
                    return new ResourceNotFoundException("Starship not found with id: " + id);
                });
        log.info("Starship retrieved successfully.");
        return StarshipMapper.toDTO(starship);
    }

    @Override
    public Page<StarshipResponseDTO> getAllStarships(Pageable pageable) {
        log.info("Entering getAllStarships() with pageable parameters");
        Page<Starship> starshipPage = starshipRepository.findAll(pageable);
        log.info("Successfully fetched {} starships", starshipPage.getNumberOfElements());
        return starshipPage.map(StarshipMapper::toDTO);
    }

    @Override
    public StarshipResponseDTO updateStarship(String id, StarshipRequestDTO requestDTO) {
        log.info("Entering updateStarship() for ID: {}", id);
        // Note: For now, update just returns what exists or regenerates since payload is empty, 
        // but typically in this model, update logic would need to change. 
        // I will throw an exception since manual updating isn't supported with empty requests.
        throw new BadRequestException("Manual updates are not supported when all fields are auto-generated.");
    }

    @Override
    public void deleteStarship(String id) {
        log.info("Entering deleteStarship() for ID: {}", id);
        if (!starshipRepository.existsById(id)) {
            log.error("Cannot delete. Starship not found with ID: {}", id);
            throw new ResourceNotFoundException("Starship not found with id: " + id);
        }
        starshipRepository.deleteById(id);
        log.info("Starship successfully deleted.");
    }
}
